print("Hey Hi!!! ")
input("What is your name? ")
input("+ Hows your day so far.. ")
input("+ Lets play a magical game of numbers.... press Enter ")
input("+ you imagine any number * dont have to tell me * JUST IMAGINE IN YOUR MIND !! press Enter ")
input("+ Get your calculator, cause you are gonna be doing some pretty magical calculations.. HEHEHE...press Enter ")
input("+ R U READY !!! ABRA KA DABRA LETS BEGIN !! press Enter ")
input("+ Guess any number...:) dont tell me what number you have selected ok! press Enter ")
input("+ Add 12 to your secret number....")
input("+ Add 10 more to your secret total number")
input("+ Substract 3 from your secret total now")
input("+ Finally substract 10 from your secret total")
name1 = input("+ Now and tell me what is your total :- ")
print("+ wait WHAT!... IS IT NOT THE NUMBER YOU IMAGINED.. ITS NOT YOUR SECRET NUMBER.. HEHEH")
print("+ ABRAAA KA DABRAAA!!!!")
name2 = int(name1)
print("+ BOOM IS THIS UR NUMBER !!!")
print(name2 - 9)
print("+ !! HOW WAS THE MAGIC !!")
print("+ Hope you enjoyed this silly game, Try again  ")
#input("code was developed by Demonsoul999")